### ISSUE TITLE
[BUG] Installation of Chardonnay 6.2-unstable runner fails

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/wine#13]
**Describe the Bug**
When enabling Pre-Release wine runners and trying to download chardonnay version 6.2-unstable, the installation fails. A notification appears that says that the dowloaded file is corrupted and I should try again. This leads to the same result

**Installation**
 - Method: Flatpak
 - Version 3.0.5

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on Hamburger Menu Button.
2. Click on the Preferences entry.
3. Scroll down to Wine Runners.
4. Click on Pre-release to enable the chardonnay 6.2-unstable option.
5. Click on the download button besides the chardonnay-6.2-unstable entry.
6. The downloads starts, but the install of the runner fails. It says that the downloaded file looks corrupted.

**Expected behaviour**
The chardonnay 6.2-unstable runner should be installed successfuly.

**Screenshots**
![Bildschirmfoto von 2021-03-03 11-00-04](https://user-images.githubusercontent.com/41188546/109788485-a89ac100-7c0f-11eb-9976-da95f01f5a6b.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 33

**Comment by mirkobrombin** [comment]
Fixed in 6.3
