### ISSUE TITLE
Caffe = Frogging-Family wine-tkg-git?

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/wine#29]
Hi! :) I was looking at the build file:

https://github.com/bottlesdevs/wine/blob/caffe/.github/workflows/build-stable-caffe.yml

It's a bit confusing that wine-tkg-git is renamed to caffe. I like the name but am just confused.

So is caffe = unmodified wine-tkg-git?

I don't know much about wine-tkg-git by the way. Looks like it has a bunch of patches on top of normal wine/wine-staging: https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git/wine-tkg-patches

Do you have any more details to share about this "caffe" and the reason it replaces vaniglia? :)

Did you notice any improvements compared to Wine-GE/Lutris-GE by GloriousEggroll?

**Comment by Bananaman** [comment]
I just looked at this again and noticed this file:

https://raw.githubusercontent.com/bottlesdevs/build-tools/main/runners/vaniglia/wine-tkg.cfg

So it's Wine-TKG with some configs.

**Comment by mirkobrombin** [comment]
Yup. We use the tkg build for caffe.

**Comment by Bananaman** [comment]
Thanks again for the answer. I think we can close this now, hehe. :) Unless you wanted to keep it open for visibility. Then feel free to re-open it.
