### ISSUE TITLE
Left mouse click stopped working entirely after playing overwatch

### ISSUE THREAD

**Issue by SpoodyTheOne** [bottlesdevs/wine#35]
As the title says, I'm completely dumbfounded by this one but somehow playing overwatch borderless windowed made my left click stop working. The issue persists after restart and sometimes it makes all mouse buttons and hover interactions stop working.

I have no idea how this happened but I couldn't find anything about it online so here I am writing the question myself.

Let me know what files to attach and I'll try my best to without my left click

**Comment by mirkobrombin** [comment]
Tracking here https://bugs.winehq.org/show_bug.cgi?id=47536
