### ISSUE TITLE
Is there a list of applied patches for caffe runner ?

### ISSUE THREAD

**Issue by TiBeN** [bottlesdevs/wine#36]
I've not found such list. 

Context: i'm looking for the least patched wine version (closest to wine stable) but with the FSR patch. Seems Lutris-fshack is the closest but there is no version higher than 7.1 available..

Does caffe includes FSR ? i tried to activate this feature in bottles using this runner without luck.

Thanks

**Comment by mirkobrombin** [comment]
The tkg recipe: https://github.com/bottlesdevs/wine/releases/tag/caffe-7.9

**Comment by TiBeN** [comment]
OK thanks. I'll close this issue.
