### ISSUE TITLE
[Bug]: weird behavior with ComboBoxRenderer using soda-7.0-9

### ISSUE THREAD

**Issue by Tiger3018** [bottlesdevs/wine#62]
Error message: `Given combination of Class, Part, and State is not defined by the current visual style.`
Sample Code: [pointfeev/CreamInstaller](https://github.com/pointfeev/CreamInstaller/blob/b0279461dbd2ce8d8b5d3363304e7428d5723627/CreamInstaller/Components/CustomTreeView.cs#L163C21-L163C37)
Environment: `soda-7.0-9`

---

Possible Solution: change the runner to `sys-wine-8.0.2` will let it go.

**Comment by xioren** [comment]
Bottles runners < 8.x are obsolete and not supported. It sounds like you already solved your issue by using a more up to date runner.

**Comment by Tiger3018** [comment]
> Bottles runners < 8.x are obsolete and not supported. It sounds like you already solved your issue by using a more up to date runner.

Confirm up-to-date versions with Proton functionality like `soda-experimental_8.0` and `caffe-8.18` don't have issues above.

Going to close this issue as resolved.
